export const apiTags = [
      { name: 'System' },
      { name: 'Auth' },
      { name: 'Family' },
      { name: 'Dashboard' },
      { name: 'Tasks' },
      { name: 'Shopping' },
      { name: 'Meals' },
      { name: 'Recipes' },
      { name: 'Pantry' },
      { name: 'Inventory' },


      { name: 'Kitchen' },
      { name: 'Calendar' },
      { name: 'Notes' },
      { name: 'Contacts' },
      { name: 'Birthdays' },
      { name: 'Budget' },
      { name: 'SplitExpenses' },
      { name: 'Documents' },
      { name: 'Housekeeping' },
      { name: 'Waste' },
      { name: 'Modules' },
      { name: 'Backup' },
      { name: 'Weather' },
      { name: 'Preferences' },
      { name: 'Reminders' },
      { name: 'Search' },
      { name: 'MCP' },
      { name: 'Push' },
      { name: 'Email' },
      { name: 'Notifications' },
      { name: 'Health' },
      { name: 'Rewards' },
      { name: 'Schedule' },
      { name: 'Quick links' },
      { name: 'Screensaver' },
      { name: 'Recipe providers' },
      { name: 'Permissions' },
];
