categories:
- productivity
icon_url: https://media.sys.truenas.net/apps/aashiyana/icons/icon.png
screenshots:
- https://media.sys.truenas.net/apps/aashiyana/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/aashiyana/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/aashiyana/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/aashiyana/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/aashiyana/screenshots/screenshot5.png
tags:
- family
- planner
- calendar
- productivity
